# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: "Vincent's Site"
subtitle: "Be a Software Development Artist!"
description: "Be a Software Development Artist!"
author: 刘文俊
nick_name: Vince
signature: Talk is cheep, show me the code.
language: zh-Hans
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://www.liuwj.me
root: /
permalink: posts/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true

highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: "    "

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:

# npm install hexo-neat --save
neat_enable: true

neat_html:
  enable: true
  exclude: 

neat_css: 
  enable: true
  exclude: 
    - '*.min.css'

neat_js:
  enable: true
  mangle: true
  output: 
  compress: 
  exclude: 
    - '*.min.js'

# npm install hexo-generator-feed --save
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content: true

# npm install hexo-algoliasearch --save
algolia:
  appId: 2W81KMSLOD
  apiKey: 2a146a809de068d9b7a07ba3fb70b4e5
  # adminApiKey: ALGOLIA_ADMIN_API_KEY
  indexName: blog
  chunkSize: 5000
  fields: 
    - title
    - subtitle
    - date
    - updated
    - slug
    - content:strip:truncate,0,5000
    - permalink
    - path
    - layout
    - tags

# npm install hexo-generator-alias --save
alias: 
  2015/08/30/hello-world/: posts/hello-world/
  2015/08/30/is-pure-android-better/: posts/is-pure-android-better/
  2015/08/31/worknote/: posts/worknote/
  2015/09/20/independent-blog-01/: posts/independent-blog-01/
  2015/09/21/independent-blog-02/: posts/independent-blog-02/
  2015/09/27/independent-blog-03/: posts/independent-blog-03/
  2015/11/08/dynamic-proxy-01/: posts/dynamic-proxy-01/
  2015/11/08/dynamic-proxy-02/: posts/dynamic-proxy-02/
  2015/11/14/FrameDAL/: posts/FrameDAL/
  2016/01/13/linq-building-an-iqueryable-provider-part-i/: posts/linq-building-an-iqueryable-provider-part-i/
  2016/01/16/linq-building-an-iqueryable-provider-part-ii/: posts/linq-building-an-iqueryable-provider-part-ii/
  2016/02/01/linq-building-an-iqueryable-provider-part-iii/: posts/linq-building-an-iqueryable-provider-part-iii/
  2016/02/03/linq-building-an-iqueryable-provider-part-iv/: posts/linq-building-an-iqueryable-provider-part-iv/
  2016/02/04/linq-building-an-iqueryable-provider-part-v/: posts/linq-building-an-iqueryable-provider-part-v/
  2016/02/13/linq-building-an-iqueryable-provider-part-vi/: posts/linq-building-an-iqueryable-provider-part-vi/
  2016/02/18/linq-building-an-iqueryable-provider-part-vii/: posts/linq-building-an-iqueryable-provider-part-vii/
  2016/02/27/linq-building-an-iqueryable-provider-part-viii/: posts/linq-building-an-iqueryable-provider-part-viii/
  2016/03/04/linq-building-an-iqueryable-provider-part-ix/: posts/linq-building-an-iqueryable-provider-part-ix/
  2016/09/03/java-reflection-black-tech/: posts/java-reflection-black-tech/
  2017/05/20/a-trap-of-comparable-interface/: posts/a-trap-of-comparable-interface/
  2017/12/16/throwing-checked-exceptions-anywhere/: posts/throwing-checked-exceptions-anywhere/
